name: Continuous Integration
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
    - run: npm install --force
    - name: Build
      run: ng build
  
